version: "3.8"

services:

  app:
    build: ./
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    ports:
      - "5436:5436"
    command: -p 5436
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres